version: "3.7"
services:
    app:
        build:
            args:
                user: lenovo
                uid: 1000
            context: .
            dockerfile: Dockerfile
        image: travellist
        container_name: travel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - travel

    mysql:
        image: mysql:8.0
        container_name: travellist-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: test1
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - travel
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            timeout: 30s
            retries: 10

    nginx:
        image: nginx:1.17-alpine
        container_name: travellist-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - travel

    php:
        image: php:8.2-fpm
        container_name: travellist-php
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - travel

networks:
    travel:
        driver: bridge
